FROM quay.io/fedora/fedora-silverblue:39
RUN cd /etc/yum.repos.d/ && curl -OL https://copr.fedorainfracloud.org/coprs/g/asahi/kernel/repo/fedora-39/group_asahi-kernel-fedora-39.repo && curl -OL https://copr.fedorainfracloud.org/coprs/g/asahi/mesa/repo/fedora-39/group_asahi-mesa-fedora-39.repo && curl -OL https://copr.fedorainfracloud.org/coprs/g/asahi/fedora-remix-branding/repo/fedora-39/group_asahi-fedora-remix-branding-fedora-39.repo && curl -OL https://copr.fedorainfracloud.org/coprs/g/asahi/fedora-remix-scripts/repo/fedora-39/group_asahi-fedora-remix-scripts-fedora-39.repo && curl -OL https://copr.fedorainfracloud.org/coprs/g/asahi/u-boot/repo/fedora-39/group_asahi-u-boot-fedora-39.repo
RUN rpm-ostree install alsa-ucm-asahi asahi-bless asahi-fwupdate asahi-scripts avahi-devel busybox codec2 crun-krun cups-devel dracut-asahi dracut-config-generic egl-utils glibc-minimal-langpack gnome-terminal gnome-terminal-nautilus google-noto-sans-arabic-vf-fonts im-chooser im-chooser-common imsettings imsettings-gsettings imsettings-libs initial-setup initial-setup-gui irqbalance json-devel keyutils-libs-devel krb5-devel libestr libfastjson librabbitmq libretls libtomcrypt libverto-devel linux-firmware-vendor lpcnetfreedv lzfse-libs m1n1 netcat openfec plymouth plymouth-graphics-libs plymouth-plugin-label plymouth-plugin-two-step plymouth-scripts plymouth-system-theme plymouth-theme-spinner pykickstart python3-asahi_firmware python3-asn1 python3-beaker python3-crypto python3-paste python3-pyOpenSSL python3-tempita qt5-qtbase-private-devel qt5-qtmultimedia-devel roc-toolkit rsyslog rsyslog-logrotate rust-kernel rust-kernel-std-static smartmontools smartmontools-selinux speexdsp-devel
RUN if [ $(uname -m) = "aarch64" ]; then rpm-ostree install grub2-efi-aa64 grub2-efi-aa64-modules shim-aa64 uboot-images-armv8 xorg-x11-drv-armsoc; fi
RUN rpm-ostree cliwrap install-to-root /
# Replace the kernel, kernel-core and kernel-modules packages.
#RUN rpm-ostree override replace kernel-16k kernel-16k-core kernel-16k-modules kernel-16k-modules-core kernel-16k-modules-extra
RUN rpm-ostree override replace --experimental --from repo='copr:copr.fedorainfracloud.org:group_asahi:kernel' kernel-16k kernel-16k-core kernel-16k-modules kernel-16k-modules-core kernel-16k-modules-extra
RUN rpm-ostree override replace fedora-asahi-remix-release fedora-asahi-remix-release-common fedora-asahi-remix-release-identity-basic fedora-asahi-remix-release-workstation update-m1n1
RUN ostree container commit

