version: '2'
pipelines:
  - name: build
    source-epoch: 1659397331
    stages:
      - type: org.osbuild.rpm
        inputs:
          packages:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-depsolve:
              architecture: $arch
              module-platform-id: $module_platform_id
              repos:
                mpp-eval: repos
              packages:
                - rpm-ostree
        options:
          gpgkeys:
            mpp-eval: gpgkeys
          exclude:
            docs: true

